name: clean_arc
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0' 


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5+1
  http: ^1.5.0


scripts:
  analyze: "flutter analyze"
  format: "dart format ."
  format:check: "dart format --output=none --set-exit-if-changed ."
  test: "flutter test"
  lint:check: "flutter analyze && dart format --output=none --set-exit-if-changed ."
  pre-commit: "flutter analyze && dart format --set-exit-if-changed . && flutter test"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.4.0
  get_it: ^7.6.4

  very_good_analysis: ^5.0.0

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


